image: ubuntu:22.04

# this runs before each job's 'script'
before_script:
  - apt update
  - apt install -y curl
  - curl -LsSf https://astral.sh/uv/install.sh | sh
  - source $HOME/.local/bin/env
  - uv sync

pages:
  stage: deploy
  script:
    - ./repo docs
    - mkdir public
    - cp -ar docs/build/html/* public
  tags:
    - pages
  artifacts:
    paths:
      - public
  only:
    - main


