name: Build Docs

on: [push, pull_request]

jobs:
  docs:
    runs-on: ubuntu-latest
    permissions:
        contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true
      - uses: actions/setup-python@v5
      - name: Install uv
        uses: astral-sh/setup-uv@v6
      - name: Install dependencies
        run: |
          uv sync
      - name: Sphinx build
        run: |
          uv run sphinx-build -M html docs/ docs/_build/